### ISSUE TITLE
How to compile/develop

### ISSUE THREAD

**Issue by moparisthebest** [CircuitMess/CircuitMess-Ringo-firmware#15]
Hello,

I'm not an Arduino developer by trade, I've compiled some Arduino projects in the past, but none like this without a .ino and with libraries in a submodule.  Can I get a few pointers with how to get set up developing/compiling my own firmware?  I have the board/libraries installed from [here](https://github.com/CircuitMess/CircuitMess-Ringo/blob/boardArduino/Installation.md) but can't seem to cleanly open it as a sketch.

Thanks much for any help!
(P.S. great hardware and software, my 8 year old daughter wanted me to tell you your 11+ age recommendation was too high :smile:)

**Comment by robbie8-bit** [comment]
Hello there, 

It seems to me like what you want to do is to edit the default firmware to your liking, correct?
This is something that is not really doable in Arduino, since Arduino IDE is mostly one-file based and it is perfect for working on a smaller project. Something like this is usually done in a more complex IDE.

I would personally recommend VS Code, which is a bit stripped down version of MS Visual Studio, yet it works much faster and you can modify it to your liking.

There is a topic on our forum in which I've already discussed this with a couple of programmers, here is the [link](https://community.circuitmess.com/t/how-to-build-the-firmware-bin-file/2629/3).

You must download the project from GitHub and import it into VS Code from where you'll be able to navigate, edit and compile everything much faster and easier. 

If you get stuck somewhere, please continue the discussion on the forum where my colleagues and community members along with myself will be able to provide you with additional support. 😃 

Well, your daughter will be doing wonders by 11 then! 😄 

Robert
