### ISSUE TITLE
Signal Bar

### ISSUE THREAD

**Issue by s700ky** [CircuitMess/CircuitMess-Ringo-firmware#9]
Works fine, strength in networks is showing 13, but at the side it just shows loading...

**Comment by robbie8-bit** [comment]
Hey,

It could be due to your network provider.

While most of them are giving return value of their name in the same format, some of them (very few) are using a somewhat different format and we didn't prepare our software to read them (every network that we tested it on worked fine).

If everything is working well, then it's really no trouble, we will fix that in the next firmware update soon.
